---
- hosts: balancer
  remote_user: root
  become: yes
  vars:
    user: deploy
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Add deploy user
      user:
        name: deploy
        shell: /bin/bash
    - name: Add SSH key to server for deploy user
      authorized_key:
        user: deploy
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT4bbzMVO1EWbvBQkSk/or7qJTcXyfwtPWQHAlmvYhyW2K5CVIqj0rx/TFnRDN7hMm7XMzKk08N6DbUzg21YnraGsbRoRA4NEqNJJjdmBz7yYkpNVNpWV6OOT6t/UIPLRMXmf6bNsvmDUDpljPb8TQXu+xJtQUdxMbzU7YgBrnnAJ9fD8oPfPaJuMIFjJ5KGtvLpb8NvZhdIiWOuddqW8M34xqMCiZpueZ8hEigT58guFRUZ1geJZKiwf1INnUdqnqruuyQ7FlfcLlM60yrq6m8Ao1F9lO2P7QNDf+RV17fYOAhA0FEweIkcBPoarSZnGo0C6878sC7LE26/VuGJDT guillermo@michelada.io"
    - name: Install NGINX
      apt:
        name: ['nginx']
        update_cache: yes
    - name: Ansible delete file example
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: copy nginx configuration file
      template:
        src: nginx.conf.balancer
        dest: /etc/nginx/conf.d/load-balancer.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      notify: restart nginx


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
